"""Jira Cloud client and payload builders."""

from __future__ import annotations

from typing import Any, Iterable

from .config import JiraConfig
from .http import BasicAuth, JsonHttpClient


def description_adf(lines: Iterable[str]) -> dict[str, Any]:
    """Build Jira Cloud Atlassian Document Format from plain text lines."""

    content: list[dict[str, Any]] = []
    for line in lines:
        if line == "":
            content.append({"type": "paragraph"})
        else:
            content.append(
                {"type": "paragraph", "content": [{"type": "text", "text": line}]}
            )
    if not content:
        content.append({"type": "paragraph"})
    return {"type": "doc", "version": 1, "content": content}


def plain_text_from_adf(adf: dict[str, Any]) -> str:
    """Return readable text from the ADF shape generated by this module."""

    lines: list[str] = []
    for paragraph in adf.get("content", []):
        if not isinstance(paragraph, dict):
            continue
        text_parts = []
        for item in paragraph.get("content", []):
            if isinstance(item, dict) and item.get("type") == "text":
                text_parts.append(str(item.get("text", "")))
        lines.append("".join(text_parts))
    return "\n".join(lines)


class JiraClient:
    """Client for Jira issue creation and updates."""

    def __init__(
        self, config: JiraConfig, *, http_client: JsonHttpClient | None = None
    ) -> None:
        self.config = config
        self.http_client = http_client or JsonHttpClient()
        self._auth_header = BasicAuth(config.email, config.api_token).header_value()

    def create_story(
        self, *, summary: str, description_lines: list[str], document_id: str
    ) -> str:
        payload = {
            "fields": self._issue_fields(summary, description_lines),
            "properties": [
                {
                    "key": "onshape",
                    "value": {"documentId": document_id},
                }
            ],
        }
        response = self._request("POST", "/rest/api/3/issue", payload)
        issue_key = response.get("key") if isinstance(response, dict) else None
        if not isinstance(issue_key, str) or not issue_key:
            raise RuntimeError(f"Jira create issue response did not include key: {response}")
        return issue_key

    def update_issue(self, issue_key: str, *, summary: str, description_lines: list[str]) -> None:
        self._request(
            "PUT",
            f"/rest/api/3/issue/{issue_key}",
            {"fields": self._issue_fields(summary, description_lines, include_project=False)},
        )

    def _issue_fields(
        self,
        summary: str,
        description_lines: list[str],
        *,
        include_project: bool = True,
    ) -> dict[str, Any]:
        fields: dict[str, Any] = {
            "summary": summary,
            "description": description_adf(description_lines),
            self.config.investments_category_field_id: {
                "value": self.config.investments_category_value
            },
        }
        if include_project:
            fields["project"] = {"key": self.config.project_key}
            fields["issuetype"] = {"name": self.config.issue_type}
        if self.config.workflow_field_id:
            fields[self.config.workflow_field_id] = {"value": self.config.workflow_value}
        return fields

    def _request(self, method: str, path: str, body: dict[str, Any]) -> Any:
        return self.http_client.request_json(
            method,
            self.config.base_url + path,
            headers={"Authorization": self._auth_header, "Content-Type": "application/json"},
            body=body,
        )
